# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=50)),
                ('imagen', models.ImageField(default='fotodefault.png', upload_to='fotos')),
                ('detalles', models.TextField(default='', max_length=100500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.TextField(max_length=50)),
                ('imagen', models.ImageField(default='categoria.png', upload_to='categorias')),
                ('descripcion', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noraefoto.Categoria'),
        ),
    ]
