# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noraefoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(default='', max_length=1500),
        ),
    ]
